### ISSUE TITLE
Add python 3.8 wheels

### ISSUE THREAD

**Issue by BengtOFFIS** [movermeyer/backports.datetime_fromisoformat#15]
Installation under python 3.8 requires compiling this package, which requires python development headers, which is annoying in CI, so please support the latest python versions with a pre-built wheel.

**Comment by domdfcoding** [comment]
This package is only required on versions of Python older than 3.7. Newer versions have `fromisoformat` built in.

If you use setuptools you can use [PEP 508 Environment Markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) to only install this package on Python 3.6 and earlier. 

For example, in your `setup.py` file:

```python
install_requires=[
   'backports-datetime-fromisoformat==1.0.0; python_version < "3.7"',
]

```

**Comment by movermeyer** [comment]
Exactly what @domdfcoding said. You don't need this package in Python 3.7+
