### ISSUE TITLE
Add Python 2.7 support

### ISSUE THREAD

**Issue by movermeyer** [movermeyer/backports.datetime_fromisoformat#2]
Extend the capability of `backports.datetime_fromisoformat` to allow usage within Python 2.7 projects.

**Comment by czechnology** [comment]
Let Python 2 rest in peace and upgrade to Python 3.

https://pythonclock.org/

**Comment by movermeyer** [comment]
@czechnology, in this case, you're likely right.

If supporting Python 2.7 was sufficiently easy to support, then we may as well, since it would only make the software more useful.

For example, if someone submitted a PR for this, I wouldn't reject it simply because it was Python 2.7.

But it currently seems unlikely that I'm going to get around to doing it myself.

**Comment by movermeyer** [comment]
Closing this, since I'm not going to do it. ~~PRs welcome!~~

Edit: PRs are no longer welcome. RIP Python 2.
