### ISSUE TITLE
Version 2 on conda-forge

### ISSUE THREAD

**Issue by mapo9** [movermeyer/backports.datetime_fromisoformat#25]
Hi,
I was wondering why the v2.0.0 is not available on conda-forge, even though the recipe was updated [here](https://github.com/conda-forge/backports-datetime-fromisoformat-feedstock).
A package I am currently creating on bioconda requires backports-datetime-fromisoformat but is not compatible with version 1.
Could you update the package retrievable via conda-forge to version 2 or do you know why it's not available?

Greetings,
Mark

**Comment by movermeyer** [comment]
Hey Mark,

I've never used, nor even looked at conda-forge, so I have no idea how it works.

Sorry and good luck,
Michael

**Comment by mapo9** [comment]
Hi Michael,

we were able to solve the problem. Thx for the reply.

Mark
