### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by movermeyer** [movermeyer/backports.datetime_fromisoformat#3]
Currently, compilation fails on Windows.

Work through the compilation errors and get `backports.datetime_fromisoformat` working for the Windows compiler

**Comment by riedel** [comment]
for me I have to patch the code to
```
 elif sys.platform == "cygwin":
                pythonapi = c.PyDLL("libpython%d.%dm.dll" % sys.version_info[:2])
```

on cygwin :(
