### ISSUE TITLE
Wheel for python 3.12

### ISSUE THREAD

**Issue by elia-bracci-hs** [movermeyer/backports.datetime_fromisoformat#35]
Is there any planned release for python 3.12 wheel?

**Comment by movermeyer** [comment]
@EliaBracciSumo Is one needed? I didn't have any plans to make one.

This library backports Python 3.11's `datetime.fromisoformat` methods to earlier versions of Python. As written, it is not needed, and indeed does nothing, in Python 3.11+.

You can limit dependencies in your `pyproject.toml`/`requirements.txt` to specific Python versions:

`backports-datetime-fromisoformat; python_version < '3.11'`

If there's a reason to publish a Python 3.11+ wheel, please let me know. I haven't heard of it.
